export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  FIXTURE_MODE_CONFLICT: "FIXTURE_MODE_CONFLICT",
  DMX_UNIVERSE_OVERFLOW: "DMX_UNIVERSE_OVERFLOW",
  SCENE_RECALCULATING: "SCENE_RECALCULATING"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
