export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  FIXTURE_VERSION_CONFLICT: "FIXTURE_VERSION_CONFLICT",
  FIXTURE_NOT_FOUND: "FIXTURE_NOT_FOUND",
  DMX_ADDRESS_OVERFLOW: "DMX_ADDRESS_OVERFLOW",
  SCENE_RECALCULATING: "SCENE_RECALCULATING",
  LEGACY_BACKFIELD_FAILED: "LEGACY_BACKFIELD_FAILED"
} as const;
